
services:
  redis:
    image: redis:7.0-alpine
    container_name: bot_redis
    # 通过环境变量设置密码（密码由脚本随机生成）
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # 暴露端口
    ports:
      - "${REDIS_PORT}:6379"
    # 启动时使用密码
    command: redis-server --requirepass ${REDIS_PASSWORD} --bind 0.0.0.0 --protected-mode no
    