services:
  redis:
    image: redis:7.0-alpine
    container_name: mockvox_redis
    # 通过环境变量设置密码（密码由脚本随机生成）
    environment:
      - REDIS_PASSWORD=123456
    # 暴露端口
    ports:
      - "6383:6379"   # 如果端口冲突修改映射到本地的端口 - "${REDIS_PORT}:6379"
  gpt-sovits:
    image: mockvox/mockvox:latest   
    container_name: mockvox
    environment:
      - REDIS_PASSWORD=123456 # 与上面设置的redis密码保持一致
      - REDIS_PORT=6383 # 与上面redis暴露端口保持一致
      - MODEL_TYPE=zh # 默认下载训练模型中文zh，其他可填值：en、can、ja、ko、full
    volumes:
      - ./data/output:/mockvox/data/output
      - ./logs:/mockvox/log
      - ./src/mockvox:/mockvox/src/mockvox
      - ./pretrained:/mockvox/pretrained
    working_dir: /mockvox
    ports:
      - "5000:5000"
    command: /bin/bash -c "chmod +x Docker/startup.sh && ./Docker/startup.sh"