[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bot"
version = "0.1.0"
description = ""
authors = [{name = "杜荣政", email = "drz@easyman.com.cn"}]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
keywords = ["bot", ""]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "fastapi>=0.95.0",
    "numpy>=2.2.4",
    "pydantic>=2.10.6",
    "fastapi>=0.115.11",
    "uvicorn>=0.34.0",
    "python-multipart>=0.0.20"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0"
]
docs = [

]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"wecom.config" = ["*.env"]